kind: pipeline
type: kubernetes
name: VCSmartApp

when:
  branch:
    - master
  event:
    - push

steps:
  - name: restore-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: villagecare-ci-sof-cache
      json_key:
        from_secret: storage_service_account
      restore: true

  - name: install-dependcy
    image: node:14.16.0-stretch
    commands:
      #      - export CI=false
      - npm i
    depends_on:
      - restore-cache
    when:
      branch:
        - master

  - name: rebuild-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: villagecare-ci-sof-cache
      json_key:
        from_secret: storage_service_account
      rebuild: true
      mount:
        - node_modules
      when:
        event: push
    depends_on:
      - install-dependcy

  - name: build-smart-app
    image: node:14.16.0-stretch
    commands:
      - export CI=false
      - npm run build
    when:
      branch:
        - master
    depends_on:
      - install-dependcy

  - name: push-smart-app
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: eu.gcr.io
      repo: eu.gcr.io/villagecare/sof
    when:
      branch:
        - master
    depends_on:
      - build-smart-app

  - name: reload all sof
    image: claranet/gcloud-kubectl-docker
    environment:
      cluster_service_account:
        from_secret: cluster_service_account
    commands:
      - echo $cluster_service_account > creds.json
      - gcloud auth activate-service-account --key-file creds.json
      - gcloud container clusters get-credentials villagecare --zone us-central1-c --project villagecare
      - kubectl -n stage rollout restart deployment stage-sof-stage
      - kubectl -n dev rollout restart deployment dev-sof-sandbox
    depends_on:
      - push-smart-app
    when:
      branch:
        - master
