---
apiVersion: v1
kind: Service
metadata:
  name: sof-dev
spec:
  selector:
    appStage: sof-dev
  ports:
    - port: 80
      name: sof-dev-http
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sof-dev

spec:
  selector:
    matchLabels:
      appStage: sof-dev
  replicas: 1
  template:
    metadata:
      labels:
        appStage: sof-dev
    spec:
      containers:
        - name: sof-dev
          image: "eu.gcr.io/villagecare/sof-dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
