---
apiVersion: v1
kind: Service
metadata:
  name: sof-sandbox
spec:
  selector:
    appStage: sof-sandbox
  ports:
    - port: 80
      name: sof-sandbox-http
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sof-sandbox
spec:
  selector:
    matchLabels:
      appStage: sof-sandbox
  replicas: 1
  template:
    metadata:
      labels:
        appStage: sof-sandbox
    spec:
      containers:
        - name: sof-sandbox
          image: "eu.gcr.io/villagecare/sof-sandbox"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
